host: ${KVSTORE_HOST}
public_port: ${KVSTORE_PUBLIC_PORT}
internal_port: ${KVSTORE_INTERNAL_PORT}
username: ${KVSTORE_USERNAME}
password: ${KVSTORE_PASSWORD}
data_path: ${KVSTORE_DATA}
logger:
  level: 0
storage:
  clean_interval: 1m
  clean_duration: 0.1s
  initial_capacity: 10_000
grpc_server:
  connection_timeout: 5s
raft:
  advertise: ${KVSTORE_ADVERTISED_ADDRESS}
  timeout: 5s
  max_pool: 3
  snapshots_retain: 2