services:
  node1:
    container_name: node1
    build: .
    environment:
      KVSTORE_HOST: 0.0.0.0
      KVSTORE_PUBLIC_PORT: 8090
      KVSTORE_INTERNAL_PORT: 3000
      KVSTORE_USERNAME: ${KVSTORE_USERNAME}
      KVSTORE_PASSWORD: ${KVSTORE_PASSWORD}
      KVSTORE_ADVERTISED_ADDRESS: node1:3000
    volumes:
      - node1_data:/home/kvstore/data
    ports:
      - "8090:8090"
    healthcheck:
      test: [ "CMD", "grpc-health-probe", "-addr=localhost:8090", "-connect-timeout", "250ms", "-rpc-timeout", "100ms" ]  # Путь к health check
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 2s
    command: [ "-verbose" ]

  node2:
    container_name: node2
    build: .
    environment:
      KVSTORE_HOST: 0.0.0.0
      KVSTORE_PUBLIC_PORT: 8090
      KVSTORE_INTERNAL_PORT: 3000
      KVSTORE_USERNAME: ${KVSTORE_USERNAME}
      KVSTORE_PASSWORD: ${KVSTORE_PASSWORD}
      KVSTORE_ADVERTISED_ADDRESS: node2:3000
    volumes:
      - node2_data:/home/kvstore/data
    ports:
      - "8091:8090"
    depends_on:
      node1:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "grpc-health-probe", "-addr=localhost:8090", "-connect-timeout", "250ms", "-rpc-timeout", "100ms" ]  # Путь к health check
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 5s
    command: [ "-join-to", "node1:8090", "-verbose" ]

  node3:
    container_name: node3
    build: .
    environment:
      KVSTORE_HOST: 0.0.0.0
      KVSTORE_PUBLIC_PORT: 8090
      KVSTORE_INTERNAL_PORT: 3000
      KVSTORE_USERNAME: ${KVSTORE_USERNAME}
      KVSTORE_PASSWORD: ${KVSTORE_PASSWORD}
      KVSTORE_ADVERTISED_ADDRESS: node3:3000
    volumes:
      - node3_data:/home/kvstore/data
    ports:
      - "8092:8090"
    depends_on:
      node1:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "grpc-health-probe", "-addr=localhost:8090", "-connect-timeout", "250ms", "-rpc-timeout", "100ms" ]  # Путь к health check
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 2s
    command: [ "-join-to", "node1:8090", "-verbose" ]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

volumes:
  node1_data:
  node2_data:
  node3_data: