services:
  node1:
    container_name: node1
    build: ../
    volumes:
      - ./node1.yaml:/home/appuser/app/config.yaml
    ports:
      - "8081:8080"
  node2:
    container_name: node2
    build: ../
    volumes:
      - ./node2.yaml:/home/appuser/app/config.yaml
    ports:
      - "8082:8080"
  node3:
    container_name: node3
    build: ../
    volumes:
      - ./node3.yaml:/home/appuser/app/config.yaml
    ports:
      - "8083:8080"