services:
  node1:
    container_name: node1
    build: ../
    volumes:
      - ./config.yaml:/home/appuser/app/config.yaml
    environment:
      - RAFT_ADVERTISE=node1:3000
      - RAFT_LOCAL_ID=node1
    ports:
      - "8081:8080"
  node2:
    container_name: node2
    build: ../
    volumes:
      - ./config.yaml:/home/appuser/app/config.yaml
    environment:
      - RAFT_ADVERTISE=node1:3000
      - RAFT_LOCAL_ID=node1
      - RAFT_LEADER_ADDRESS=node1:8080
    ports:
      - "8082:8080"
    depends_on:
      - node1
  node3:
    container_name: node3
    build: ../
    volumes:
      - ./config.yaml:/home/appuser/app/config.yaml
    environment:
      - RAFT_ADVERTISE=node1:3000
      - RAFT_LOCAL_ID=node1
      - RAFT_LEADER_ADDRESS=node1:8080
    ports:
      - "8083:8080"
    depends_on:
      - node1